### PR TITLE
Added in original documents for learning to optimize and optimizing optimization.

### PR DESCRIPTION
**Pull request by genixpro**
Since the original links went down to these documents, just adding original copies in word.

### CODE REVIEW

**Comment by marload** [comment]
Thank you for your contribution!

But personally, I dont think it's good way to include `docx` files in the repository.
So I think we should replace it with another link.

**Comment by genixpro** [comment]
@marload Your probably right, its a quick solution. Unfortunately these two articles are not hosted anywhere else except on my other bayesian optimization repository, Hypermax. We could adjust the links to point to those copies: 

https://raw.githubusercontent.com/electricbrainio/hypermax/master/docs/Optimizing%20Optimization.docx
and
https://raw.githubusercontent.com/electricbrainio/hypermax/master/docs/Learning%20to%20Optimize.docx

**Comment by genixpro** [comment]
The new owner of electric brain took down all the blog articles and doesn't seem interested in putting these two articles back up, because they are too technical for his audience

**Comment by marctorsoc** [comment]
> @marload Your probably right, its a quick solution. Unfortunately these two articles are not hosted anywhere else except on my other bayesian optimization repository, Hypermax. We could adjust the links to point to those copies:
> 
> https://raw.githubusercontent.com/electricbrainio/hypermax/master/docs/Optimizing%20Optimization.docx
> and
> https://raw.githubusercontent.com/electricbrainio/hypermax/master/docs/Learning%20to%20Optimize.docx

please turn them into markdown if you want them to be in the repo. Docx is the evil

**Comment by marctorsoc** [comment]
any progress on this @genixpro ?

**Pull request closed without merging**
