### PR TITLE
progressbar with tqdm

### PR DESCRIPTION
**Pull request by PhilipMay**
I added the progressbar. See #454 
It can not be turned off and is on by default.
But I can add this if wanted.

The progressbar also shows the best (lowest loss).

Would be happy for feedback.

Philip

### CODE REVIEW

**Comment by PhilipMay** [comment]
I am working on it. Will tell you when I am done.
The distributed setup (mongo etc.) should work too. I will investigate it.

**Comment by maxpumperla** [comment]
awesome, looking forward to it.

**Comment by PhilipMay** [comment]
> btw, how does this look in distributed setup (mongo etc.)?

Well, for mongo you pass a `MongoTrials` object to `fmin` instead of a "normal" `Trials` object. See here: https://github.com/hyperopt/hyperopt/wiki/Parallelizing-Evaluations-During-Search-via-MongoDB#2-use-mongotrials

I am pretty sure that they are handled by the same loop that is inside my progress bar.

**Comment by PhilipMay** [comment]
I am done with my work here. The python 2.7 build is still broken though. :-(
What do you suggest?

**Comment by PhilipMay** [comment]
When should I extend the documentation? https://github.com/hyperopt/hyperopt.github.io
After release?

**Comment by maxpumperla** [comment]
@PhilipMay I tested locally, works with 2.7. Let's fix travis after this PR. Same goes for docs.

Thanks for the contribution, please keep it up! :)

**Comment by PhilipMay** [comment]
Was fun to implement it and discuss it here. ! :-)

**Comment by trevorwelch** [comment]
Thankful for this! Great job!

**Comment by uduse** [comment]
This is a nice feature to have, but unexpected output like this breaks doctests. Before this PR, I managed to silence hyperopt's output by setting the logger verbose level. However, it no longer works now. Since I also think having `show_progressbar=True` by default is a great idea, I suggest instead of using plain tqdm, [pass tqdm to the logger](https://github.com/tqdm/tqdm/issues/313) so that projects do not care about hyperopt's output get this nice feature, and projects fiddled with hyperopt's logger level have consistent output behavior.

**Pull request merged**
