### PR TITLE
Fix: Use journal instead of j on MongoClient for MongoTrials

### LINKED ISSUE #836: MongoDB error: Unknown option j
When I tried to optimize the hyper-parameters using hyperopt and Mongodb, hower, while the following codes were runned in spyder, the program ran wrong.
       from hyperopt.mongoexp import MongoTrials
       trials =  MongoTrials(arg='mongo://localhost:27017/foo_db/jobs', exp_key=('exp1'))
The tips were as follows:
      File "E:\Program\Anaconda3\lib\site-packages\pymongo\common.py", line 144, in raise_config_error
             raise ConfigurationError("Unknown option %s" % (key,))
I tried to exam whether the MongoDB had installed successfully. The following codes were used:
      from pymongo import MongoClient
     client=MongoClient()
     client
     MongoClient('localhost', 27017)
The results are:
     MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

### PR DESCRIPTION
**Pull request by german1608**
Closes #836 

---

Hello! First PR around here!

I updated the `j` key to `journal`, and also updated the requirements for `pymongo` to be at least `4.0.0`

I don't know if I need to make any other changes on this PR such as version increases. I'll let that decision to the maintainers.

### CODE REVIEW

**Comment by german1608** [comment]
This might also close #845. This PR is more of a replacement for it.

**Review by vad0 — APPROVED** [review]

**Comment by cyclux** [comment]
Could you please merge this fix?

**Comment by vad0** [comment]
I can't merge this since I am not a code owner. I ended up using optuna, which does all the same stuff and even more, and which is kept up to date. https://github.com/optuna/optuna

**Comment by cyclux** [comment]
I understand, thanks for the tip, will check it out!

**Review by lu-wang-dl — APPROVED** [review]

**Pull request merged**
