### PR TITLE
Fix verbosity for fmin with tpe.suggest

### PR DESCRIPTION
**Pull request by marctorrellas**
fmin used to have an unused argument `verbose`. With this PR all the messages can be removed with verbose=False. Doing this also removes the progressbar.
I also introduced a verbose argument for `tpe.suggest`

As a byproduct of this PR:
- Some pieces of code in `if 0` were removed
- Some strings exceeding max line length were split

### CODE REVIEW

**Comment by marctorrellas** [comment]
@maxpumperla  `pip install .[SparkTrials]` is failing for 2.7. Any idea? Tests are passing for 3.5 and 3.6

**Comment by maxpumperla** [comment]
@marctorrellas thanks. no worries, travis is sometimes a bit flaky.

**Comment by marctorsoc** [comment]
Do you mean that the `verbose` param in `fmin` is not enough to control the verbosity? Can you show a minimum example program and what's your issue?

**Comment by mtwhitecamel** [comment]
@skoeb 's problem is algo(tpe.suggest by default) use a param named verbose, which controlling several logging function,
but when fmin invoke algo() in line 278: new_trial = algo(new_ids, self.domain, trials, self.rstate.integers(2 ** 31 - 1)),
it doesn't pass self.verbose to tpe.suggest,
maybe change to new_trial = algo(new_ids, self.domain, trials, self.rstate.integers(2 ** 31 - 1), verbose=self.verbose) is more reasonable

**Pull request merged**
