### PR TITLE
support uniformint

### PR DESCRIPTION
**Pull request by fukatani**
This PR is suggestion for supporting `uniformint` and `quniformint`
for integer hyper parameter such as `max_depth` of XGB.
(See #253 )

I know same function is achievable by using `hp.choice`, this PR can be declined.

### CODE REVIEW

**Comment by maxpumperla** [comment]
@jaberg are we interested in this? I think it's very valuable! @fukatani would you mind updating the branch so we can consider merging? Thanks!

**Comment by jaberg** [comment]
I don't understand this PR and I wonder if @fukatani is misunderstanding quniform. quniform can already be used to truncate uniform draws to e.g. integer values, and it returns them as floating point numbers. It would be reasonable to further call scope.int on the return value from such a quniform call if the quantization value was an integer - is that the intent here? It isn't exactly what's written.

**Comment by fukatani** [comment]
I'm sorry I misunderstand `quniform` and I want to merge only `uniformint`.
`quniformint` has no sense.

I think `uniformint` is useful in some cases where `integer` hyper parameters are only allowed.

I merged and resolved conflict.
I appreciate if you merge it.

**Comment by jaberg** [comment]
How about implementing uniformint as a scope.int cast of hp_quniform with q hard-coded to be 1.0 ?

**Comment by fukatani** [comment]
Thanks! I did it.

**Pull request merged**
