### PR TITLE
Revert "Python 3 compatibility"

### PR DESCRIPTION
**Pull request by jaberg**
Reverts hyperopt/hyperopt#272

This change breaks py27 "No module named builtins" appears in both the tests and import of main repo, not quite ready to roll yet.

### CODE REVIEW

**Comment by jaberg** [comment]
@maxpumperla I hate to revert your good work - but the current master doesn't even import on py27, could you fix it? Or hit merge here?

**Comment by maxpumperla** [comment]
we just need to add `future` to `setup.py`, that's all. Sorry I didn't check this properly in a venv. I'm currently not on a computer, but can fix it later. Otherwise, it's just this one line one has to add.

**Comment by jaberg** [comment]
Cool, I'll watch for a PR and give it a try.

**Comment by jeremykohn** [comment]
@jaberg @maxpumperla 

Are there plans to re-add Python 3 compatibility? [#275](https://github.com/hyperopt/hyperopt/pull/275) doesn't seem to do so.

I ask because in Python 3 I'm getting the error `TypeError: fmin() got an unexpected keyword argument 'rseed'`. (Related issue: https://github.com/maxpumperla/hyperas/issues/40)

**Pull request closed without merging**
