### PR TITLE
Support python3

### PR DESCRIPTION
**Pull request by lucasb-eyer**
It passes `nosetest hyperopt`, but I wasn't able to run `nosetest hyperopt` in py2 since I don't have a py2-scipy environment available.

One thing to note is that I had to fix the incompatibilities in `pyll` by hand because I couldn't figure out how to make `setup.py` also run `2to3` on additional packages.

### CODE REVIEW

**Comment by shjb** [comment]
Looks great @lucasb-eyer thanks for this!

**Comment by jaberg** [comment]
Looks great @lucasb-eyer thanks for this!

**Comment by jseabold** [comment]
What version of Python 3 was this on? I see a lot of errors because things like

```
import fmin as fmin_module
```

get fixed to 

```
from . import fmin as fmin_module
```

and this imports from `__init__.py` which has already imported the fmin function. Other things like this don't work, on 3.4 at least, because `i` isn't in the scope.

```
[(i,) for i in range(5)]
del i
```

**Comment by jseabold** [comment]
Shadowing the module name with the function name is tricky. It's not immediately obvious to me how to fix this in a backwards compatible way.

**Comment by lucasb-eyer** [comment]
Sorry, I don't remember the version, but it was likely 3.3 or 3.4, but I agree it's odd I didn't see the problems you found.

**Pull request merged**
