### PR TITLE
Fix broken spark plugin test

### PR DESCRIPTION
**Pull request by WeichenXu123**
Fix broken spark plugin test:

* Fix CI command for spark test
* Fix a failure spark test `test_trial_run_info` broken by https://github.com/hyperopt/hyperopt/pull/821

### CODE REVIEW

**Comment by WeichenXu123** [comment]
Note: Current travis CI don't run test_spark, @maxpumperla Could you help enable it ?

I manually run:
```
PYSPARK_PIN_THREAD=false pytest hyperopt/tests/integration/test_spark.py
PYSPARK_PIN_THREAD=true pytest hyperopt/tests/integration/test_spark.py
```
to confirm all tests passed.

CC @dbczumar

**Comment by maxpumperla** [comment]
@WeichenXu123 I introduced the `integration` folder to separate mongo and spark tests. You see how we run tests here:

https://github.com/hyperopt/hyperopt/blob/master/.github/workflows/pre-commit.yml#L38

If you want to run tests upstream, either add a new line in the above YAML, or consider moving the test.

**Comment by WeichenXu123** [comment]
@maxpumperla  YAML updated.

**Comment by maxpumperla** [comment]
@WeichenXu123 awesome, thank you!

**Pull request merged**
