### PR TITLE
new tutorial init: 02. MultipleParameterTutorial

### PR DESCRIPTION
**Pull request by marload**
Create a second tutorial. Please review, thank you.

https://github.com/hyperopt/hyperopt/blob/dev-tutorial/tutorial/02.MultipleParameterTutorial.ipynb

### CODE REVIEW

**Comment by maxpumperla** [comment]
@marload thanks, this is great, especially for putting in the effort with visualisations and maths typesetting.

**Comment by maxpumperla** [comment]
@marload btw, can we find a way to let github pages render these notebooks? If so, we could try to include them as "getting started guide" in our docs.

**Comment by marload** [comment]
@maxpumperla By any chance, is this what you're looking for?
https://stackoverflow.com/questions/43110659/how-to-add-ipython-notebook-to-github-pages

**Comment by maxpumperla** [comment]
@marload yes, exactly. so we convert your tutorials to markdown and have them in the `docs` folder. we're using `mkdocs` for the doc generation, so once the YAML file etc. are adapted we can update docs with `mkdocs gh-deploy`.

**Comment by marload** [comment]
@maxpumperla Okay, I'll try. And, I'd like to suggest that you create a new Web page for HyperOpt. Using an open-source template by modifying it, I think we can create a much better-looking page without taking too much time.

**Comment by maxpumperla** [comment]
@marload sure, sure. We're currently using mkdocs, if you find a theme for that that you like, we can use that. otherwise we could move to a generic github-hosted `jekyll` page. If you have one you like, we can work on that. Doesn't really matter as long as the jekyll plugins used are white-listed by github. so just go ahead and pick one :D

**Comment by marctorsoc** [comment]
this is amazing @marload . I'd really like to get those notebooks in the main page. They are way easier to follow than the current documentation. Let me know if you need a hand with this

**Comment by marload** [comment]
@marctorsoc Thank you. Then, could you help me register this tutorial with Document?

**Comment by marctorsoc** [comment]
sorry for the delay. I don't know how it works atm, but will take a look this weekend. I'll send an email and we talk over there to organise this :)

**Comment by marctorsoc** [comment]
email sent @marload

**Comment by marload** [comment]
@marctorsoc 


I didn't receive the email. Could you check it again? My email is rladhkstn8@gmail.com.

**Comment by marctorsoc** [comment]
@marload that's the one I sent it to. Send me an email otherwise

**Pull request merged**
