### PR TITLE
do not log the MongoDB password in plain text

### PR DESCRIPTION
**Pull request by tgpfeiffer**
I think from a security point of view it makes sense to not log the password in plain text.

### CODE REVIEW

**Comment by tgpfeiffer** [comment]
Can I do anything to get this merged soon? I think the PR is rather straightforward to review.

**Comment by michaelmior** [comment]
This logging was explicitly added for debugging purposes. Logging completely since logging `****` doesn't provide any useful information. It would at least be good to log whether a password was provided.

**Comment by tgpfeiffer** [comment]
I see. So what do you think about something like:
```python
if password is not None:
  logger.info('PASS ***')
```

**Comment by michaelmior** [comment]
That should work :)

**Comment by tgpfeiffer** [comment]
@michaelmior Fixed, could you please have another look? Thank you!

**Pull request merged**
